FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.5.20 /uv /usr/local/bin/uv
COPY pyproject.toml uv.lock README.md ./
COPY app ./app
COPY tests ./tests

RUN uv sync --frozen

CMD ["uv", "run", "pytest", "tests/firestore", "-rs"]
