from typing import Protocol

from .models import AuditEvent, LlmApiToken, Record


class RecordRepository(Protocol):
    """Storage contract for Markdown records."""

    def get_by_slug(self, space: str, slug: str) -> Record | None: ...
    def list_children(self, space: str, parent_id: str | None) -> list[Record]: ...
    def create(self, record: Record) -> Record: ...
    # Raises KeyError when record_id does not identify an existing record.
    def update(self, record_id: str, record: Record, actor_id: str = "system") -> Record: ...


class LlmTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> LlmApiToken | None: ...
    def save(self, token: LlmApiToken) -> LlmApiToken: ...
    def revoke(self, token_id: str) -> None: ...


class AuditEventRepository(Protocol):
    def append(self, event: AuditEvent) -> AuditEvent: ...
