from typing import Protocol

from .models import Record


class RecordRepository(Protocol):
    """Storage contract for Markdown records."""

    def get_by_slug(self, space: str, slug: str) -> Record | None: ...
    def list_children(self, space: str, parent_id: str | None) -> list[Record]: ...
    def create(self, record: Record) -> Record: ...
    # Raises KeyError when record_id does not identify an existing record.
    def update(self, record_id: str, record: Record) -> Record: ...
